---
services:
  # Managed services
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: masstransit/rabbitmq:${DOCKER_RABBITMQ_VERSION}
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=${SERVICEBUS_MANAGEMENT_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${SERVICEBUS_MANAGEMENT_PASSWORD}
  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch:${DOCKER_MEILISEARCH_VERSION}
    environment:
      - MEILI_MASTER_KEY=${MEILISEARCH_MASTER_KEY}
    restart: always
    ports:
      - 7700:7700

  # Authentication services
  authentication-database:
    container_name: authentication-database
    hostname: authdb
    image: "postgres:${DOCKER_POSTGRES_VERSION}"
    environment:
      - POSTGRES_USER=${AUTH_DB_USER}
      - POSTGRES_PASSWORD=${AUTH_DB_PASSWORD}
      - POSTGRES_DB=${AUTH_DB_NAME}
    ports:
      - 5432:5432
    restart: always

  authentication-core:
    container_name: authentication-core
    hostname: authcore
    image: registry.supertokens.io/supertokens/supertokens-postgresql:${DOCKER_SUPERTOKENS_CORE_VERSION}
    ports:
      - 3567:3567
    environment:
      POSTGRESQL_CONNECTION_URI: "postgresql://${AUTH_DB_USER}:${AUTH_DB_PASSWORD}@authdb:5432/${AUTH_DB_NAME}"
    restart: always

  # Microshop.NET services
  gateway:
    container_name: gateway
    hostname: gateway
    build:
      context: .
      dockerfile: infrastructure/Dockerfile.dotnet
      args:
        - SERVICE_NAME=gateway
    environment:
      - ReverseProxy__Routes__authentication__Match__Hosts__0=auth.localhost
      - ReverseProxy__Clusters__authentication__Destinations__authentication__Address=http://authsvc
      - ReverseProxy__Routes__admin__Match__Hosts__0=admin.localhost
      - ReverseProxy__Clusters__admin__Destinations__admin__Address=http://admin
      - ReverseProxy__Routes__api__Match__Hosts__0=api.localhost
      - ReverseProxy__Clusters__api__Destinations__api__Address=http://api
      - ReverseProxy__Clusters__index__Destinations__index__Address=http://meilisearch:7700
      - ReverseProxy__Routes__index__Match__Hosts__0=index.localhost
    restart: always
    ports:
      - 80:80
  products:
    container_name: products
    hostname: products
    build:
      context: .
      dockerfile: infrastructure/Dockerfile.dotnet
      args:
        - SERVICE_NAME=products
    environment:
      - Servicebus__BaseUrl=rabbitmq
      - Servicebus__ManagementUsername=${SERVICEBUS_MANAGEMENT_USERNAME}
      - Servicebus__ManagementPassword=${SERVICEBUS_MANAGEMENT_PASSWORD}
    restart: always
    ports:
      - 5001:80
  indexing:
    container_name: indexing
    hostname: indexing
    build:
      context: .
      dockerfile: infrastructure/Dockerfile.dotnet
      args:
        - SERVICE_NAME=indexing
    environment:
      - Servicebus__BaseUrl=rabbitmq
      - Servicebus__ManagementUsername=${SERVICEBUS_MANAGEMENT_USERNAME}
      - Servicebus__ManagementPassword=${SERVICEBUS_MANAGEMENT_PASSWORD}
      - Indexing__BaseUrl=http://meilisearch:7700/
      - Indexing__ApiKey=${MEILISEARCH_MASTER_KEY}
      - Indexing__IndexingIntervalInSeconds=3600
    restart: always
    ports:
      - 5003:80
  pricing:
    container_name: pricing
    hostname: pricing
    build:
      context: .
      dockerfile: infrastructure/Dockerfile.dotnet
      args:
        - SERVICE_NAME=pricing
    environment:
      - Servicebus__BaseUrl=rabbitmq
      - Servicebus__ManagementUsername=${SERVICEBUS_MANAGEMENT_USERNAME}
      - Servicebus__ManagementPassword=${SERVICEBUS_MANAGEMENT_PASSWORD}
    restart: always
    ports:
      - 5002:80
  authentication-service:
    container_name: authentication-service
    hostname: authsvc
    build:
      context: .
      dockerfile: infrastructure/Dockerfile.authentication
    environment:
      - AUTHENTICATION_CORE_URL=http://authcore:3567
      - AUTHENTICATION_BACKEND_HOST=authentication-service
      - AUTHENTICATION_BACKEND_PORT=80
      - GATEWAY_URL=http://localhost:5000
      - WEBSITE_URL=http://localhost:3000
      - DASHBOARD_USER_EMAIL=${DASHBOARD_USER_EMAIL}
      - DASHBOARD_USER_PASSWORD=${DASHBOARD_USER_PASSWORD}
      - ADMIN_KEY=${ADMIN_KEY}
    restart: always
    ports:
      - 5004:80
  api:
    container_name: api
    hostname: api
    build:
      context: .
      dockerfile: infrastructure/Dockerfile.dotnet
      args:
        - SERVICE_NAME=api
    environment:
      - Servicebus__BaseUrl=rabbitmq
      - Servicebus__ManagementUsername=${SERVICEBUS_MANAGEMENT_USERNAME}
      - Servicebus__ManagementPassword=${SERVICEBUS_MANAGEMENT_PASSWORD}
      - Authentication__BaseUrl=http://authsvc
      - Authentication__Issuer=http://localhost:5000/auth
    restart: always
    ports:
      - 5005:80
  admin:
    container_name: admin
    hostname: admin
    build:
      context: .
      dockerfile: infrastructure/Dockerfile.dotnet
      args:
        - SERVICE_NAME=admin
        - PROJECT_NAME=Web
    environment:
      - Authentication__BaseUrl=http://authsvc
      - UserManagement__BaseUrl=http://authcore:3567
      - DataManagement__BaseUrl=http://api
    restart: always
    ports:
      - 5006:8080
