---
services:
  rabbitmq:
    container_name: rabbitmq
    image: masstransit/rabbitmq:latest
    ports:
      - 15672:15672
      - 5672:5672
    restart: always
  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch:v1.0.2
    environment:
      - MEILI_MASTER_KEY=${MEILISEARCH_MASTER_KEY}
    ports:
      - 7700:7700
    restart: always
  gateway:
    container_name: gateway
    build: 
      context: .
      dockerfile: infrastructure/Dockerfile.backend
      args:
        - SERVICE_NAME=Gateway
        - SERVICE_DLL=Proxy.dll
    ports:
      - 8001:80