---
services:
  rabbitmq:
    container_name: rabbitmq
    image: masstransit/rabbitmq:latest
    ports:
      - 15672:15672
      - 5672:5672
    restart: always
  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch:v1.0.2
    environment:
      - MEILI_MASTER_KEY=${MEILISEARCH_MASTER_KEY}
    ports:
      - 7700:7700
    restart: always
  gateway:
    container_name: gateway
    build: 
      context: .
      dockerfile: infrastructure/Dockerfile.backend
      args:
        - SERVICE_NAME=Gateway
        - SERVICE_DLL=Proxy.dll
    ports:
      - 8080:80
    environment:
      - Proxy__Clusters__products__Destinations__productsApi__Address=http://products
  products:
    container_name: products
    build: 
      context: .
      dockerfile: infrastructure/Dockerfile.backend
      args:
        - SERVICE_NAME=Products
        - SERVICE_DLL=Listener.dll
    environment:
      - Servicebus__BaseUrl=rabbitmq
      - Servicebus__ManagementUsername=${SERVICEBUS_MANAGEMENT_USERNAME}
      - Servicebus__ManagementPassword=${SERVICEBUS_MANAGEMENT_PASSWORD}
  indexing:
    container_name: indexing
    build: 
      context: .
      dockerfile: infrastructure/Dockerfile.backend
      args:
        - SERVICE_NAME=Indexing
        - SERVICE_DLL=Indexer.dll
    environment:
      - Servicebus__BaseUrl=rabbitmq
      - Servicebus__ManagementUsername=${SERVICEBUS_MANAGEMENT_USERNAME}
      - Servicebus__ManagementPassword=${SERVICEBUS_MANAGEMENT_PASSWORD}
      - Indexing__BaseUrl=http://meilisearch:7700/
      - Indexing__ApiKey=${MEILISEARCH_MASTER_KEY}
      - Indexing__IndexingIntervalInSeconds=3600