---
services:
  rabbitmq:
    container_name: rabbitmq
    image: masstransit/rabbitmq:latest
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=${SERVICEBUS_MANAGEMENT_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${SERVICEBUS_MANAGEMENT_PASSWORD}
  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch:latest
    environment:
      - MEILI_MASTER_KEY=${MEILISEARCH_MASTER_KEY}
    restart: always
    ports:
      - 7700:7700
  products:
    container_name: products
    build:
      context: .
      dockerfile: infrastructure/Dockerfile.backend
      args:
        - SERVICE_NAME=products
        - SERVICE_DLL=Listener.dll
    environment:
      - Servicebus__BaseUrl=rabbitmq
      - Servicebus__ManagementUsername=${SERVICEBUS_MANAGEMENT_USERNAME}
      - Servicebus__ManagementPassword=${SERVICEBUS_MANAGEMENT_PASSWORD}
  indexing:
    container_name: indexing
    build:
      context: .
      dockerfile: infrastructure/Dockerfile.backend
      args:
        - SERVICE_NAME=indexing
        - SERVICE_DLL=Indexer.dll
    environment:
      - Servicebus__BaseUrl=rabbitmq
      - Servicebus__ManagementUsername=${SERVICEBUS_MANAGEMENT_USERNAME}
      - Servicebus__ManagementPassword=${SERVICEBUS_MANAGEMENT_PASSWORD}
      - Indexing__BaseUrl=http://meilisearch:7700/
      - Indexing__ApiKey=${MEILISEARCH_MASTER_KEY}
      - Indexing__IndexingIntervalInSeconds=3600
