name: Continuous Deployment (Template)
concurrency: cd-${{ github.workflow }}

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      service-name:
        required: true
        type: string
    secrets:
      azureClientId:
        required: true
      azureClientSecret:
        required: true
      azureSubscriptionId:
        required: true
      azureTenantId:
        required: true

jobs:
  deploy:
    name: Deploy ${{ inputs.service-name }} to the ${{ inputs.environment }} environment
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.azureClientId }}","clientSecret":"${{ secrets.azureClientSecret }}","subscriptionId":"${{ secrets.azureSubscriptionId }}","tenantId":"${{ secrets.azureTenantId }}"}'

      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: "rg-microshop-${{ inputs.environment }}"
          cluster-name: "aks-microshop-${{ inputs.environment }}"

      - name: Deploy serivce
        uses: azure/k8s-deploy@v4
        with:
          manifests: ./infrastructure/kubernetes/${{ inputs.service-name }}.yaml
