FROM golang:trixie AS build-stage

WORKDIR /app
COPY apps/authentication/go.mod apps/authentication/go.sum ./
RUN go mod download
COPY apps/authentication/ ./
RUN CGO_ENABLED=0 GOOS=linux go build -o /auth

FROM alpine:latest AS build-release-stage

WORKDIR /
COPY --from=build-stage /auth /auth
ENTRYPOINT ["/auth"]