FROM golang:bookworm AS build-stage

WORKDIR /app
COPY backend/authentication/go.mod backend/authentication/go.sum ./
RUN go mod download
COPY backend/authentication/ ./
RUN CGO_ENABLED=0 GOOS=linux go build -o /auth

FROM alpine:latest AS build-release-stage

WORKDIR /
COPY --from=build-stage /auth /auth
ENTRYPOINT ["/auth"]