---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      # - path: /
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: dns-service
      #       port:
      #         number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dns-service
            port:
              number: 7700
---
apiVersion: v1
kind: Service
metadata:
  name: dns-service
spec:
  selector:
    dns: dns-service
  ports:
  - port: 80
    name: gateway
  - port: 7700
    name: meilisearch
