apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-deployment
spec:
  selector:
    matchLabels:
      app: products-app
  template:
    metadata:
      labels:
        app: products-app
    spec:
      containers:
        - name: products
          image: physer/microshop-products:main
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          env:
            - name: Servicebus__BaseUrl
              value: "rabbitmq-service"
            - name: Servicebus__Port
              value: "5672"
            - name: Servicebus__ManagementUsername
              valueFrom:
                secretKeyRef:
                  name: SERVICEBUS_MANAGEMENT_USERNAME
                  key: SERVICEBUS_MANAGEMENT_USERNAME
            - name: Servicebus__ManagementPassword
              valueFrom:
                secretKeyRef:
                  name: SERVICEBUS_MANAGEMENT_PASSWORD
                  key: SERVICEBUS_MANAGEMENT_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: products-service
spec:
  selector:
    app: products-app
  ports:
    - port: 80
