name: Build and publish authentication service template
concurrency: ci-authentication

on:
  workflow_call:
    secrets:
      docker-username:
        required: true
      docker-password:
        required: true

jobs:
  build-and-publish-services:
    name: Build and publish authentication service
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/authentication
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "stable"

      - name: Build
        run: go build -v

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.docker-username }}
          password: ${{ secrets.docker-password }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: physer/microshop-authentication

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./infrastructure/Dockerfile.authentication
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
