name: Continuous Deployment (Template)
concurrency: cd-${{ github.workflow }}

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      azureClientId:
        required: true
      azureClientSecret:
        required: true
      azureSubscriptionId:
        required: true
      azureTenantId:
        required: true
  workflow_run:
    workflows: [continuous_integration, test_provision_resources, production_provision_resources]
    types: completed

jobs:
  prepare_aks_credentials:
    if: ${{ github.event.continuous_integration.conclusion == 'success' }} && ${{ github.event.test_provision_resources.conclusion == 'success' }} && ${{ github.event.production_provision_resources.conclusion == 'success' }}
    name: Prepare AKS deployment credentials
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: azure/setup-kubectl@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.azureClientId }}","clientSecret":"${{ secrets.azureClientSecret }}","subscriptionId":"${{ secrets.azureSubscriptionId }}","tenantId":"${{ secrets.azureTenantId }}"}'

      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: "rg-microshop-${{ inputs.environment }}"
          cluster-name: "aks-microshop-${{ inputs.environment }}"
