name: Deploy the Products service
concurrency: products

permissions:
  id-token: write
  contents: read

on:
  workflow_run:
    workflows:
      ["Build and publish the Products service", "Deploy generic resources"]
    types:
      - completed
  workflow_dispatch:

jobs:
  provision-products:
    name: Deploy the Products service
    uses: ./.github/workflows/reusable-provision.yaml
    with:
      environment: ${{ vars.ENVIRONMENT }}
      infrastructure-path: internal/products
      service-name: products
    secrets: inherit
