name: Deploy the Pricing service
concurrency: pricing

permissions:
  id-token: write
  contents: read

on:
  workflow_run:
    workflows:
      ["Build and publish the Pricing service", "Deploy generic resources"]
    types:
      - completed
  workflow_dispatch:

jobs:
  provision-pricing:
    name: Deploy the Pricing service
    uses: ./.github/workflows/reusable-provision.yaml
    with:
      environment: ${{ vars.ENVIRONMENT }}
      infrastructure-path: internal/pricing
      service-name: pricing
    secrets: inherit
