name: Deploy the Products service
concurrency: products

permissions:
  id-token: write
  contents: read

on:
  workflow_run:
    workflows: ["Build and publish the Products service"]
    types:
      - completed
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "infrastructure/terraform/internal/products/**"
      - "infrastructure/terraform/modules/**"

jobs:
  provision-products:
    name: Deploy the Products service
    uses: ./.github/workflows/reusable-provision.yaml
    with:
      environment: ${{ vars.ENVIRONMENT }}
      infrastructure-path: internal/products
      service-name: products
    secrets: inherit
