name: Deploy the Pricing service
concurrency: pricing

permissions:
  id-token: write
  contents: read

on:
  workflow_run:
    workflows: ["Build and publish the Pricing service"]
    types:
      - completed
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "infrastructure/terraform/internal/pricing/**"
      - "infrastructure/terraform/modules/**"

jobs:
  provision-pricing:
    name: Deploy the Pricing service
    uses: ./.github/workflows/reusable-provision.yaml
    with:
      environment: ${{ vars.ENVIRONMENT }}
      infrastructure-path: internal/pricing
      service-name: pricing
    secrets: inherit
