name: Deploy required services
concurrency: deploy

on:
  workflow_dispatch:
  # Temporarily disabled until proper filters are applied
  # push:
  #   branches:
  #     - main

jobs:
  build-and-publish-services:
    name: Build and publish services
    runs-on: ubuntu-latest
    strategy:
      matrix:
        services:
          [
            { name: indexing, entrypoint: Indexer },
            { name: products, entrypoint: Listener },
          ]
    defaults:
      run:
        working-directory: backend/${{ matrix.services.name }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: physer/microshop-${{ matrix.services.name }}

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./infrastructure/Dockerfile.backend
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            SERVICE_NAME=${{ matrix.services.name }}
            SERVICE_DLL=${{ matrix.services.entrypoint }}.dll

  deploy_terraform_resources:
    name: Deploy resources to Azure using Terraform
    needs: build-and-publish-services
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      TF_VAR_environment: ${{ vars.ENVIRONMENT }}
    defaults:
      run:
        working-directory: infrastructure/terraform
    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Initialize Terraform
        run: terraform init -backend-config="config.azure.tfbackend"

      - name: Set Terraform workspace
        run: terraform workspace select -or-create production

      - name: Plan Terraform
        run: terraform plan -no-color

      - name: Apply Terraform
        run: terraform apply -auto-approve
