name: Deploy the Indexing service
concurrency: indexing

permissions:
  id-token: write
  contents: read

on:
  workflow_run:
    workflows: ["Build and publish the Indexing service"]
    types:
      - completed
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "infrastructure/terraform/internal/indexing/**"
      - "infrastructure/terraform/modules/**"

jobs:
  provision-indexing:
    name: Deploy the Indexing service
    uses: ./.github/workflows/reusable-provision.yaml
    with:
      environment: ${{ vars.ENVIRONMENT }}
      infrastructure-path: internal/indexing
      service-name: indexing
    secrets: inherit
