name: Deploy generic resources
concurrency: generic

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "infrastructure/terraform/generic/**"
      - "infrastructure/terraform/modules/**"

jobs:
  provision-generic-resources:
    uses: ./.github/workflows/reusable-provision.yaml
    with:
      service-name: generic-resources
      infrastructure-path: generic
      environment: ${{ vars.ENVIRONMENT }}
      rabbitmq-docker-image-version: ${{ vars.DOCKER_RABBITMQ_VERSION }}
      meilisearch-docker-image-version: ${{ vars.DOCKER_MEILISEARCH_VERSION }}
    secrets: inherit
