name: Deploy generic resources
concurrency: generic

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - "**/.github/*"

jobs:
  provision-generic-resources:
    uses: ./.github/workflows/provision.yaml
    with:
      service-name: generic-resources
      infrastructure-path: generic
      environment: ${{ vars.ENVIRONMENT }}
    secrets: inherit
