name: Deploy services receiving incoming traffic
concurrency: traffic

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "infrastructure/terraform/external/**"
      - "infrastructure/terraform/dns-proxy/**"
      - "infrastructure/terraform/modules/**"
      - "apps/api/**"
      - "apps/authentication/**"
      - "apps/gateway/**"

jobs:
  build-publish-api:
    name: Build and publish the API
    uses: ./.github/workflows/dotnet-service.yaml
    with:
      service-name: api
      service-path: apps/api
    secrets: inherit

  build-publish-authentication:
    name: Build and publish the Authentication service
    uses: ./.github/workflows/authentication-service.yaml
    secrets: inherit

  build-publish-gateway:
    name: Build and publish the Gateway
    uses: ./.github/workflows/dotnet-service.yaml
    with:
      service-name: gateway
      service-path: apps/gateway
    secrets: inherit

  provision-indexing:
    name: Deploy the services serving traffic
    needs:
      [build-publish-api, build-publish-authentication, build-publish-gateway]
    uses: ./.github/workflows/provision.yaml
    with:
      environment: ${{ vars.ENVIRONMENT }}
      infrastructure-path: external
      service-name: incoming-traffic
    secrets: inherit
