name: Indexing - Continuous Deployment

on:
  workflow_dispatch:
  push:
    paths:
      - "backend/Indexing/**"
      - ".github/**"
    branches:
      - main

jobs:
  products_continuous_deployment:
    uses: Physer/Microshop.NET/.github/workflows/continuous-deployment.yaml@main
    with:
      service-directory: backend/Indexing
      docker-image-name: microshop-indexing
      service-name: Indexing
      service-dll: Indexer.dll
    secrets:
      dockerUsername: ${{ secrets.DOCKER_USERNAME }}
      dockerPassword: ${{ secrets.DOCKER_PASSWORD }}
