name: Indexing - Continuous Integration

on:
  workflow_dispatch:
  push:
    paths:
      - 'backend/Indexing/**'
      - '.github/**'

jobs:
  products_continuous_integration:
    uses: Physer/Microshop.NET/.github/workflows/continuous-integration.yaml@main
    with:
      service-directory: backend/Indexing
      docker-image-name: microshop-indexing
      service-name: Indexing
      service-dll: Indexer.dll
    secrets:
      dockerUsername: ${{ secrets.DOCKER_USERNAME }}
      dockerPassword: ${{ secrets.DOCKER_PASSWORD }}