name: Indexing - Continuous Deployment

on:
  workflow_dispatch:
  push:
    paths:
      - "backend/Indexing/**"
      - ".github/**"
    branches:
      - main

jobs:
  indexing_continuous_integration:
    name: Continuous Integration - Indexing service
    uses: Physer/Microshop.NET/.github/workflows/continuous-integration.yaml@main
    with:
      service-directory: backend/Indexing
      docker-image-name: microshop-indexing
      service-name: Indexing
      service-dll: Indexer.dll
    secrets:
      dockerUsername: ${{ secrets.DOCKER_USERNAME }}
      dockerPassword: ${{ secrets.DOCKER_PASSWORD }}
  test_indexing_continuous_deployment:
    name: Continuous Deployment (Test) - Indexing service
    uses: Physer/Microshop.NET/.github/workflows/continuous-deployment.yaml@main
    needs: indexing_continuous_integration
    with:
      environment: test
    secrets:
      azureClientId: ${{ secrets.AZURE_CLIENT_ID }}
      azureClientSecret: ${{ secrets.AZURE_CLIENT_SECRET }}
      azureSubscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      azureTenantId: ${{ secrets.AZURE_TENANT_ID }}
  production_products_continuous_deployment:
    name: Continuous Deployment (Production) - Indexing service
    uses: Physer/Microshop.NET/.github/workflows/continuous-deployment.yaml@main
    needs: test_indexing_continuous_deployment
    with:
      environment: production
    secrets:
      azureClientId: ${{ secrets.AZURE_CLIENT_ID }}
      azureClientSecret: ${{ secrets.AZURE_CLIENT_SECRET }}
      azureSubscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      azureTenantId: ${{ secrets.AZURE_TENANT_ID }}
