name: Build libraries
concurrency: libraries

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "libs/**"

jobs:
  build-mockhttpclient-library:
    name: Build the MockHttpClient library
    uses: ./.github/workflows/reusable-dotnet-library.yaml
    with:
      service-path: libs/mockhttpclient
    secrets: inherit

  build-inlinewebapplicationfactory-library:
    name: Build the InlineWebApplicationFactory library
    uses: ./.github/workflows/reusable-dotnet-library.yaml
    with:
      service-path: libs/inlinewebapplicationfactory
      execute-tests: false
    secrets: inherit

  build-containerconfiguration-library:
    name: Build the ContainerConfiguration library
    uses: ./.github/workflows/reusable-dotnet-library.yaml
    with:
      service-path: libs/containerconfiguration
      execute-tests: false
    secrets: inherit
