name: Products - Continuous Integration

on:
  workflow_dispatch:
  push:
    paths:
      - 'backend/Products/**'
      - '.github/**'

jobs:
  products_continuous_integration:
    uses: Physer/Microshop.NET/.github/workflows/continuous-integration.yml@main
    with:
      service-directory: backend/Products
      docker-image-name: microshop-products
      service-name: Products
      service-dll: Listener.dll
    secrets:
      dockerUsername: ${{ secrets.DOCKER_USERNAME }}
      dockerPassword: ${{ secrets.DOCKER_PASSWORD }}