name: Products - Continuous Deployment

on:
  workflow_dispatch:
  push:
    paths:
      - "backend/Products/**"
      - ".github/**"
    branches:
      - main

jobs:
  products_continuous_deployment:
    uses: Physer/Microshop.NET/.github/workflows/continuous-deployment.yaml@main
    with:
      service-directory: backend/Products
      docker-image-name: microshop-products
      service-name: Products
      service-dll: Listener.dll
    secrets:
      dockerUsername: ${{ secrets.DOCKER_USERNAME }}
      dockerPassword: ${{ secrets.DOCKER_PASSWORD }}
