name: Provision resources

on:
  workflow_dispatch:
  push:
    paths:
      - "infrastructure/**"
      - ".github/**"
    branches:
      - main

jobs:
  production_provision_resources:
    name: Production - Provision resources
    uses: Physer/Microshop.NET/.github/workflows/provisioning.yaml@main
    with:
      environment: production
    secrets:
      azureClientId: ${{ secrets.AZURE_CLIENT_ID }}
      azureClientSecret: ${{ secrets.AZURE_CLIENT_SECRET }}
      azureSubscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      azureTenantId: ${{ secrets.AZURE_TENANT_ID }}
      meilisearchApiKey: ${{ secrets.MEILISEARCH_API_KEY }}
      rabbitMqUsername: ${{ secrets.RABBITMQ_USERNAME }}
      rabbitMqPassword: ${{ secrets.RABBITMQ_PASSWORD }}
