name: Provision resources (Template)
concurrency: provisioning

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      location:
        required: false
        type: string
        default: West Europe
    secrets:
      azureClientId:
        required: true
      azureClientSecret:
        required: true
      azureSubscriptionId:
        required: true
      azureTenantId:
        required: true

jobs:
  provision_resources:
    defaults:
      run:
        working-directory: infrastructure/terraform
    name: Provision resources using Terraform
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.azureClientId }}
      ARM_CLIENT_SECRET: ${{ secrets.azureClientSecret }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.azureSubscriptionId }}
      ARM_TENANT_ID: ${{ secrets.azureTenantId }}
      TF_VAR_environment: ${{ inputs.environment }}
      TF_VAR_location: ${{ inputs.location }}
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - name: Terraform workspace select
        id: workspace
        run: terraform workspace select -or-create ${{ inputs.environment }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init --backend-config=config.azure.tfbackend

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -compact-warnings

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve
