name: "[Reusable] Build and deploy a .NET library to NuGet"
concurrency: ci-${{ inputs.service-path }}

on:
  workflow_call:
    inputs:
      service-path:
        required: true
        type: string

jobs:
  build-and-publish-services:
    name: Build and publish library (${{ inputs.service-path }})
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.service-path }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Package library
        run: dotnet pack -c Release -o package --no-build

      - name: Publish to NuGet registry
        run: dotnet nuget push "**/package/**/*.nupkg" --api-key ${{ secrets.NUGET_APIKEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
